apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    ver: 1.1
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: mysql
      ver: 1.1
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
        ver: 1.1
    spec:
      containers:
        name: mysql
        image: mysql:5.6
        ports:
          containerPort: 3306
          


